# -*- coding: utf-8 -*-
"""interseccion_xander.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WnUkU5jA-D8FFZ2ZudlP_x5oDB8mHYyU
"""

from pyspark.context import SparkContext

sc = SparkContext('local', 'test')

sc2 = SparkContext('local', 'test2')

sc2.stop()

var = sc.parallelize(["b", "a", "c"])

var.map(lambda x: (x, 1)).collect()

var_context = var.map(lambda x: (x, 1))

var_context.collect()

rdd_1 = sc.parallelize([1, 1, 2, 3])

rdd_2 = sc.parallelize([6, 7, 8, 9])

var_general = rdd_1.union(rdd_2)

var_general.collect()

var_general = rdd_1.union(rdd_1)

var_general.collect()
